# 2 Algèbre linéaire

Python permet aussi de réaliser un grand nombre d’opérations en algèbre linéaire à l'aide du package numpy, il faut donc l'importer.

In [21]:
import numpy as np

## 2.1 Vecteurs

### 2.1.1 Définition

Pour créer un vecteur en Python (qui sera par défault un vecteur **ligne**), on utilise ce qui s'appelle un **numpy ndarray**.

In [23]:
x = np.array([[1,2,3]])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[[1 2 3]]


Ici nous avons assigné le vecteur (1, 2, 3) à la variable x.
<br>
**Remarque :** Les doubles crochets sont utilisés ici pour voir un vecteur comme une matrice composé d'une seule ligne.

Pour obtenir un vecteur **colonne**, on prend la **transposée** d'un vecteur ligne à l'aide de la commande **.T**.

In [24]:
x = np.array([[1,2,3]])
x.T

array([[1],
       [2],
       [3]])

### 2.1.2 Opérations sur les vecteurs

On peut additionner des vecteurs de même longueur entre eux à l'aide de l'opération **+**.

In [25]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
x + y

array([[5, 7, 9]])

Et multiplier un vecteur par un scalaire à l'aide de l'opération <b>*</b>.

In [26]:
x = np.array([[1,2,3]])
3 * x

array([[3, 6, 9]])

## 2.2 Matrices

Python permet d'effectuer un grand nombre d'opérations sur les matrices.

### 2.2.1 Définitions

Par extention à la définition de vecteur vu plus haut, on peut définir une matrice en python.
<br>
Les éléments d'une ligne sont séparés par des virgules, et les colonnes sont séparés par des crochets.

In [27]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2.2.2 Opération sur les matrices

Voici les principales opérations que l’on peut effectuer en Python sur les matrices.

**Addition et multiplication par un scalaire**
<br>
**L’addition** de deux matrices se calcule avec le symbole **+**.

In [28]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
A + B

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

**la multiplication d’une matrice par un scalaire** se calculent avec le symbole <b>*</b>.

In [29]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
l = 3
A * l

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

**Multiplication matricielle**
<br>
**La multiplication matricielle** (lorsque elle est possible) s'effectue avec la commande **matmul()** de numpy.

In [30]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.matmul(A,B)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Lorsque la multiplication matricielle est impossible, un message d'erreur apparaît.

In [31]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6]])
np.matmul(A,B)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

**Attention :** L'opération <b>*</b> multiplie deux matrices **élément par élément**.

In [32]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
A*B

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

**Puissance d'une matrice**
<br>
Pour élever **une matrice A à la puissance n**, on utilise la commande **numpy.linalg.matrix_power(A, n)**.

In [33]:
A = np.array([[1,2],[3,4]])
np.linalg.matrix_power(A,5)

array([[1069, 1558],
       [2337, 3406]])

**Rang d'une matrice**
<br>
**Le rang** d'une matrice A s'obtient à l'aide de la commande **numpy.linalg.matrix_rank(A)**.

In [34]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.matrix_rank(A)

2

**Matrice transposée**
<br>
De manière similaire à un vecteur, **la transposée** d'une matrice A s'obtient à l'aide de la commande **A.T**.

In [35]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Déterminant**
<br>
**Le déterminant** d'une matrice A s'obtient à l'aide de la commande **numpy.linalg.det(A)**.

In [36]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(A)

6.66133814775094e-16

**Attention :** Ici le déterminant ne donne pas exactement 0 car Python donne **une approximation numérique** du déterminant.

In [37]:
B = np.array([[1,2,1],[4,5,6],[7,8,9]])
np.linalg.det(A)

6.66133814775094e-16

**Matrice inverse**
<br>
**L'inverse** d'une matrice A, si elle existe, s'obtient à l'aide de la commande **numpy.linalg.inv(A)**.

In [38]:
A = np.array([[1,2,1],[4,5,6],[7,8,9]])
np.linalg.inv(A)

array([[-0.5       , -1.66666667,  1.16666667],
       [ 1.        ,  0.33333333, -0.33333333],
       [-0.5       ,  1.        , -0.5       ]])

On peut vérifier que le produit d'une matrice et de son inverse donne bien la matrice identitié.

In [39]:
A = np.array([[1,2,1],[4,5,6],[7,8,9]])
B = np.linalg.inv(A)
np.matmul(A,B)

array([[ 1.00000000e+00, -2.22044605e-16,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00,  4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

**Valeurs et vecteurs propres**
<br>
**les valeurs et vecteurs propres** d'une matrice à s'obtiennent à l'aide de la commande **numpy.linalg.eig(A)**

In [40]:
A = np.array([[1,2,1],[4,5,6],[7,8,9]])
np.linalg.eig(A)

(array([15.28732829+0.j        , -0.14366415+0.60978893j,
        -0.14366415-0.60978893j]),
 array([[-0.13352141+0.j        ,  0.72616402+0.j        ,
          0.72616402-0.j        ],
        [-0.53752837+0.j        , -0.2665448 +0.4112075j ,
         -0.2665448 -0.4112075j ],
        [-0.83260752+0.j        , -0.29739816-0.37960823j,
         -0.29739816+0.37960823j]]))

Le premier array corresponds aux **vecteurs propres**.
<br>
Le deuxième array corresponds **aux vecteurs propres**.

### 2.2.3 Résolution d'un système linéaire
La résolution du système linéaire **Ax = b** s'obtient à l'aide de la commande **numpy.linalg.solve(A,b)**.

Par exemple, la résolution du système :
<br>

x + 2y = 1
<br>
3x + 5y = 2
<br>

s'effectue de la manière suivante :

In [41]:
A = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(A, b)

array([-1.,  1.])